name: getPing
version: '1.0'
main: wiki.thesarthakdev.getPing.getPing
api-version: '1.21'
authors: [Sarthak Kumar]
description: A lightweight and optimized plugin to check player ping with minimal performance impact.
commands:
  ping:
    description: Check your or another player's ping.
    usage: /ping [player]
    permission: getping.use
  pingreload:
    description: Reload the plugin's configuration.
    usage: /pingreload
    permission: getping.reload
  pingtop:
    description: Display the top 10 players with the best ping.
    usage: /pingtop
    permission: getping.pingtop
permissions:
  getping.use:
    description: Allows players to use the /ping command and right-click ping check.
    default: true
  getping.reload:
    description: Allows reloading the plugin's configuration.
    default: op
  getping.pingtop:
    description: Allows players to use the /pingtop command.
    default: true